version: '3'

services:
  apache:
    build: ./docker/build/apache
    ports:
      - "8000:80"
    depends_on:
      - mysql
    volumes:
      - ./docker/conf/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./docker/conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/conf/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
      - .:/var/www/symfony

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/conf/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: symfony

  phpmyadmin:
    ports:
      - "8001:80"
    image: nazarpc/phpmyadmin
    depends_on:
      - mysql
